name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create_pr
        uses: actions/github-script@v6
        with:
          script: |
            const { App } = require('@octokit/app');
            const { Octokit } = require('@octokit/core');

            // Load GitHub App credentials from secrets
            const appId = process.env.APP_ID;
            const privateKey = process.env.PRIVATE_KEY;
            const installationId = process.env.INSTALLATION_ID;

            // Create an authenticated Octokit instance
            const app = new App({ appId, privateKey });
            const installationAccessToken = await app.getInstallationAccessToken({ installationId });

            const octokit = new Octokit({ auth: installationAccessToken });

            // Create a pull request
            const { data: pullRequest } = await octokit.request('POST /repos/{owner}/{repo}/pulls', {
              owner: 'MerihanAhmedM',
              repo: 'gold',
              title: 'Automated PR from common-workflows',
              head: 'pr-branch',
              base: 'main',
              body: 'This is an automated PR created by a workflow.'
            });

            console.log('Pull request created successfully:', pullRequest.html_url);
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
