name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: MerihanAhmedM/gold
          branch: pr-branch
          title: "Automated PR from common-workflows"
          body: "This is an automated PR created by a workflow."
