name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
           node-version: '16'
           
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}  # Ensure APP_ID is set correctly in your secrets
          private-key: ${{ secrets.PRIVATE_KEY }}  # Ensure PRIVATE_KEY is set correctly in your secrets
          owner: MerihanAhmedM  # Replace with your GitHub username or organization
          repositories: '["MerihanAhmedM/gold"]'  # List of repositories if needed
          skip-token-revoke: true  # Optional, depends on your needs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: MerihanAhmedM/gold
          title: My Pull Request
          body: This is a pull request created by GitHub Actions
          head: main
          base: main
