name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
           node-version: '16'
           
      - name: Checkout code
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{vars.APP_ID}}
          private-key: ${{ secrets.PRIVATE_KEY}}
          installation-id: ${{vars.INSTALLATION_ID}}
      - name: create pull req
        uses:  peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.create-app-token.outputs.token }}
          repository: MerihanAhmedM/gold
          title: My Pull Request
          body: This is a pull request created by GitHub Actions
          head: main
          base: main


        
