name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate JWT and Create Pull Request
        run: |
          # Install jq for JSON parsing
          sudo apt-get install -y jq

          # Generate a JWT
          JWT=$(python -c "
import jwt
import time

# Load private key
private_key = '''${{ secrets.PRIVATE_KEY }}'''

# Generate JWT
payload = {
    'iat': int(time.time()),
    'exp': int(time.time()) + 600,
    'iss': '${{ secrets.APP_ID }}'
}

token = jwt.encode(payload, private_key, algorithm='RS256')
print(token.decode('utf-8'))
")

          # Get an installation access token
          ACCESS_TOKEN=$(curl -X POST https://api.github.com/app/installations/${{ secrets.INSTALLATION_ID }}/access_tokens \
            -H "Authorization: Bearer $JWT" \
            -H "Accept: application/vnd.github.machine-man-preview+json" \
            | jq -r .token)

          # Create a pull request
          curl -X POST https://api.github.com/repos/MerihanAhmedM/gold/pulls \
            -H "Authorization: token $ACCESS_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "title": "Automated PR from common-workflows",
              "head": "pr-branch",
              "base": "main",
              "body": "This is an automated PR created by a workflow."
            }'
