name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: MerihanAhmedM/gold
          branch: pr-branch
          title: "Automated PR from common-workflows"
          body: "This is an automated PR created by a workflow."

      - name: Check Pull Request Status
        id: check_pr
        uses: actions/github-script@v6
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: 'MerihanAhmedM:pr-branch'
            });
            if (prs.length > 0) {
              console.log('Pull request created successfully.');
            } else {
              console.log('No pull request found.');
            }
