name: Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code from common-workflows
      uses: actions/checkout@v3  

    - name: Create GitHub App Token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v3
      with:   
          application_id: ${{ vars.APP_ID }}  # Ensure APP_ID is set correctly in your secrets
          application_private_key: ${{ secrets.PRIVATE_KEY }}  # Ensure PRIVATE_KEY is set correctly in your secrets
          owner: MerihanAhmedM  # Replace with your GitHub username or organization
          repositories: '["MerihanAhmedM/gold"]'  # List of repositories if needed
          skip-token-revoke: true  # Optional, depends on your needs

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
          token: ${{ steps.app-token.outputs.token }}
          repository: MerihanAhmedM/gold
          title: My Pull Request
          body: This is a pull request created by GitHub Actions
          head: main
          base: main
